name: Build AuraGit OS

on:
  push:
    branches: [ "main" ]

jobs:
  build-rom:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Обновили до v4 для стабильности

    - name: Freeing up disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        # Освобождаем место под Android

    - name: Install Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev libxml2-utils unzip python3

    - name: Run Build Script
      run: |
        chmod +x build_auragit.sh
        ./build_auragit.sh

    - name: Upload Finished System Image
      uses: actions/upload-artifact@v4 # <--- ИСПРАВЛЕНО ТУТ (с v3 на v4)
      with:
        name: auragit-system-image
        path: out/target/product/generic_x86_64/system.img
